#!/bin/sh

# This script is used to deploy the site to the gh-pages branch
# when pushing to the remote repository.

remote="$1"
url="$2"

npm run deploy
if [ $? -ne 0 ]; then
  echo "npm run deploy failed, not pushing"
  exit 1
fi